### ISSUE TITLE
could not get it to work in new GameMaker

### ISSUE THREAD

**Issue by serup** [DragoniteSpam-GameMaker-Tutorials/3DTutorial5-OBJ-Models#1]
I tried cloning the project, then having GameMaker convert the project -- no issues found when converting, however starting it did not show anything, so something is wrong

The version I converted to was
IDE v2.3.1.542 Runtime v2.3.1.409

**Comment by serup** [comment]
> I tried cloning the project, then having GameMaker convert the project -- no issues found when converting, however starting it did not show anything, so something is wrong
> 
> The version I converted to was
> IDE v2.3.1.542 Runtime v2.3.1.409

After making sure that the check mark in Room Settings (Clear Display Buffer) - then it was possible to see the loaded object

![image](https://user-images.githubusercontent.com/874896/112857391-16bc9180-90b1-11eb-8611-3f3bb016a885.png)
![image](https://user-images.githubusercontent.com/874896/112857596-4bc8e400-90b1-11eb-9d1f-d58f14611156.png)

**Comment by DragoniteSpam** [comment]
Hi, sorry for the delay. Glad you figured out this was an issue with the way GameMaker handles the display buffer - but this was explained in the video description, and in more detail in the pinned comment on the video, with the necessary changes in the [23](https://github.com/DragoniteSpam-GameMaker-Tutorials/3DTutorial5-OBJ-Models/tree/23) branch in the repository.

With that said, I'm just going to merge the 23 branch into master now. There's basically no reason for anyone to use anything older than that now anyway.
